apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad-api
  template:
    metadata:
      labels:
        app: bad-api
    spec:
      containers:
      - name: app
        image: nginx:0.0   # invalid tag to trigger ImagePullBackOff
        ports:
        - containerPort: 80
